# go install
# docker run
#     --rm
#     -t
#     -v $(pwd):/app
#     -w /app
#     --user $(id -u):$(id -g)
#     -v $(go env GOCACHE):/.cache/go-build
#     -e GOCACHE=/.cache/go-build
#     -v $(go env GOMODCACHE):/.cache/mod
#     -e GOMODCACHE=/.cache/mod
#     -v ~/.cache/golangci-lint:/.cache/golangci-lint
#     -e GOLANGCI_LINT_CACHE=/.cache/golangci-lint
#     golangci/golangci-lint:v2.4.0
#     golangci-lint run

version = "2"


[run]
# Timeout for total work, e.g. 30s, 5m, 5m30s.
# If the value is lower or equal to 0, the timeout is disabled.
# Default: 0 (disabled)
#timeout = "5m"
# The mode used to evaluate relative paths.
# It's used by exclusions, Go plugins, and some linters.
# The value can be:
# - `gomod`: the paths will be relative to the directory of the `go.mod` file.
# - `gitroot`: the paths will be relative to the git root (the parent directory of `.git`).
# - `cfg`: the paths will be relative to the configuration file.
# - `wd` (NOT recommended): the paths will be relative to the place where golangci-lint is run.
# Default: cfg
relative-path-mode = "gomod"
# If set, we pass it to "go list -mod={option}". From "go help modules":
# If invoked with -mod=readonly, the go command is disallowed from the implicit
# automatic updating of go.mod described above. Instead, it fails when any changes
# to go.mod are needed. This setting is most useful to check that go.mod does
# not need updates, such as in a continuous integration and testing system.
# If invoked with -mod=vendor, the go command assumes that the vendor
# directory holds the correct copies of dependencies and ignores
# the dependency descriptions in go.mod.
#
# Allowed values: readonly|vendor|mod
# Default: ""
modules-download-mode = "readonly"

# Number of operating system threads (`GOMAXPROCS`) that can execute golangci-lint simultaneously.
# Default: 0 (automatically set to match Linux container CPU quota and
# fall back to the number of logical CPUs in the machine)
concurrency = 12


[linters]
#default = "all"
#enable=[]
#disable=[]


# Defines a set of rules to ignore issues.
# It does not skip the analysis, and so does not ignore "typecheck" errors.
[linters.exclusions]
# Log a warning if an exclusion rule is unused.
# Default: false
warn-unused = true
# Predefined exclusion rules.
# Default: []
presets = [
    "comments",
    "std-error-handling",
    "common-false-positives",
    "legacy"
]
paths = [
    "cmd/.*",
]

[linters.settings]

[[linters.exclusions.rules]]
path = ".*"
linters = ["unused"]
[[linters.exclusions.rules]]
linters = ["staticcheck"]
text = "S1025"

[linters-settings.stylecheck]
checks = ["all", "-ST1003"]
dot-import-whitelist = [""]



[formatters]
enable = [
    "gofmt",
    "goimports",
    "gofumpt",
]

[formatters.exclusions]
warn-unused = true
paths = [
    "cmd/.*",
]
