networks:
  myapp:
    name: "net_myapp"
    driver: bridge
    ipam:
      config:
        - subnet: 99.99.97.0/24
          gateway: 99.99.97.254

services:
  app-server:
    image: golang-example/ubuntu2204/app:v202509181257
    ports:
      - "8080:8080"
      #- "65534:65534"
    volumes:
      #- ./logs:/myapp/logs
      - ./certs:/myapp/certs
      - ./configs:/myapp/configs
      - ./db:/myapp/db
      - /home/user/codes/go/src/github.com/jianlu8023/golang-example/test/baasca:/home/user/codes/go/src/github.com/jianlu8023/golang-example/test/baasca
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - myapp
    container_name: app-server
    stop_grace_period: 120s # 设置容器停止的宽限期为60秒
    command: server --config configs/server.yaml --type docker --debug --version
    restart: unless-stopped
  app-client:
    image: golang-example/ubuntu2204/app:v202509181257
    # ports:
      #- "65533:65533"
    volumes:
      #- ./logs:/myapp/logs
      - ./certs:/myapp/certs
      - ./configs:/myapp/configs
      - ./db:/myapp/db
      #- /home/user/codes/go/src/github.com/jianlu8023/golang-example/test/baasca:/home/user/codes/go/src/github.com/jianlu8023/golang-example/test/baasca
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - myapp
    container_name: app-client
    command: client --config configs/client.yaml --type docker --debug --version
    restart: unless-stopped
    depends_on:
      app-server:
        condition: service_healthy
