// 注意设置go环境变量中的架构和系统为本地系统，然后安装如下两个插件
// go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
// go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
// 检查安装情况
// protoc-gen-go --version
// protoc-gen-go-grpc --version
// 运行生成代码
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative pkg/control/grpc/pb/message.proto

// twirp
// go install github.com/twitchtv/twirp/protoc-gen-twirp@latest
// go install github.com/golang/protobuf/protoc-gen-go@latest // 过时 推荐使用下方
// google.golang.org/protobuf/cmd/protoc-gen-go@latest
// 在message.proto 文件夹下执行
// protoc --twirp_out=. --go_out=. ./message.proto
// https://github.com/twitchtv/twirp

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.32.1
// source: pkg/control/grpc/pb/message.proto

package pb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MessageService_SendMessageBidi_FullMethodName = "/pb.MessageService/SendMessageBidi"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	// 双向流 RPC（用于大请求 + 大响应）
	SendMessageBidi(ctx context.Context, opts ...grpc.CallOption) (MessageService_SendMessageBidiClient, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendMessageBidi(ctx context.Context, opts ...grpc.CallOption) (MessageService_SendMessageBidiClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], MessageService_SendMessageBidi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceSendMessageBidiClient{ClientStream: stream}
	return x, nil
}

type MessageService_SendMessageBidiClient interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type messageServiceSendMessageBidiClient struct {
	grpc.ClientStream
}

func (x *messageServiceSendMessageBidiClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServiceSendMessageBidiClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	// 双向流 RPC（用于大请求 + 大响应）
	SendMessageBidi(MessageService_SendMessageBidiServer) error
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) SendMessageBidi(MessageService_SendMessageBidiServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessageBidi not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_SendMessageBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServiceServer).SendMessageBidi(&messageServiceSendMessageBidiServer{ServerStream: stream})
}

type MessageService_SendMessageBidiServer interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type messageServiceSendMessageBidiServer struct {
	grpc.ServerStream
}

func (x *messageServiceSendMessageBidiServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServiceSendMessageBidiServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessageBidi",
			Handler:       _MessageService_SendMessageBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/control/grpc/pb/message.proto",
}
