// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: pkg/control/grpc/pb/message.proto

package pb

import (
	"context"
	// "google.golang.org/grpc"
	"github.com/hxx258456/ccgo/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	// 双向流 RPC（用于大请求 + 大响应）
	SendMessageBidi(ctx context.Context, opts ...grpc.CallOption) (MessageService_SendMessageBidiClient, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendMessageBidi(ctx context.Context, opts ...grpc.CallOption) (MessageService_SendMessageBidiClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], "/pb.MessageService/SendMessageBidi", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceSendMessageBidiClient{stream}
	return x, nil
}

type MessageService_SendMessageBidiClient interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type messageServiceSendMessageBidiClient struct {
	grpc.ClientStream
}

func (x *messageServiceSendMessageBidiClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServiceSendMessageBidiClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	// 双向流 RPC（用于大请求 + 大响应）
	SendMessageBidi(MessageService_SendMessageBidiServer) error
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) SendMessageBidi(MessageService_SendMessageBidiServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessageBidi not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_SendMessageBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServiceServer).SendMessageBidi(&messageServiceSendMessageBidiServer{stream})
}

type MessageService_SendMessageBidiServer interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type messageServiceSendMessageBidiServer struct {
	grpc.ServerStream
}

func (x *messageServiceSendMessageBidiServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServiceSendMessageBidiServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessageBidi",
			Handler:       _MessageService_SendMessageBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/control/grpc/pb/message.proto",
}
