datasource:
  enabled: false
  data_source_type: sqlite3
  db_username: username
  db_password: password
  db_host: localhost
  db_port: 3306
  db_path: ./db/gm-fabric.db
  max_idle_conn: 10
  max_open_conn: 50
  log_in_console: true
docker:
  enabled: false
  host: unix:///var/run/docker.sock
  default_timeout: 5
grpc:
  enabled: true
  server:
    host: 0.0.0.0:65533
    max_recv_msg_size: 5242880
    max_send_msg_size: 5242880
    chunk_size: 4194304
    tls_enabled: true
    tls_cert_file: ./certs/gserver.crt
    tls_key_file: ./certs/gserver.key
    tls_rca_cert_file: ./certs/root-ca.crt
  client:
    host: 127.0.0.1:65534
    max_call_recv_msg_size: 5242880
    max_call_send_msg_size: 5242880
    chunk_size: 4194304
    call_timeout: 99999
    tls_enabled: true
    tls_cert_file: ./certs/gclient.crt
    tls_key_file: ./certs/gclient.key
    tls_rca_cert_file: ./certs/root-ca.crt
http:
  enabled: false
  address: :8080
  context_path: example
  run_mode: release
  tls_enabled: true
  tls_cert_file: ./certs/hserver.crt
  tls_key_file: ./certs/hserver.key
  tls_rca_cert_file: ./certs/root-ca.crt
libp2p:
  enabled: true
  listen_addr:
    - /ip4/0.0.0.0/tcp/2001
    - /ip6/::1/tcp/2001
    - /ip4/0.0.0.0/udp/2001/quic-v1
    - /ip4/127.0.0.1/udp/2001/quic-v1
    - /ip4/0.0.0.0/udp/2001/quic-v1/webtransport
    - /ip4/0.0.0.0/udp/2001/webrtc-direct
    - /dns4/localhost/udp/2001/ws
  identity:
    peer_id: 12D3KooWB9vcdUVqj3doZb2mQtmrXfwRF4ZcrNtquA77PQqZGZci
    privkey: CAESQAi11XdBy0ogf7CgJNNicEk0mKM/2A9k7QtA1jmQW1RfE95o0U/gmG1RraWA38kdmHXExAkKFr0UgvowIYQ4Qa8=
  protocol_id: /gm-fabric/chat/1.0.0
  service_tag: gm-fabric-deployment
  bootstrap_list:
  #- "dns4/127.0.0.1/udp/2000/quic-v1/p2p/12D3KooWEmsdj6kGx8cpcjZWd4QG4bh4FZGuBEiUULWRgScyNHwe"
logger:
  default_log_level: debug
  stack_log_level: fatal
  print_format: console
  file_path: ./logs/app.log
  max_age: 7
  rotation_time: 1
  logger_level:
    grpc: debug
    libp2p: debug
    main: debug
    docker: debug
ants_pool:
  enabled: false
  # 线程池大小
  pool_size: 8
  # 最大线程池
  max_pool_size: 16
  # 工作协程过期时间
  expiry_duration: 60
  # 是否预分配工作协程
  pre_alloc: true
  # 是否非阻塞模式
  nonblocking: true
