grpc:
  server:
    host: 127.0.0.1:65534
    max_recv_msg_size: 5242880
    max_send_msg_size: 5242880
    chunk_size: 4194304
    tls_enabled: true
    tls_cert_file: ./certs/gserver.crt
    tls_key_file: ./certs/gserver.key
    tls_rca_cert_file: ./certs/root-ca.crt
  client:
    host: 127.0.0.1:65533
    max_call_recv_msg_size: 5242880
    max_call_send_msg_size: 5242880
    chunk_size: 4194304
    call_timeout: 99999
    tls_enabled: true
    tls_cert_file: ./certs/gclient.crt
    tls_key_file: ./certs/gclient.key
    tls_rca_cert_file: ./certs/root-ca.crt
http:
  address: :8080
  context_path: example
  run_mode: release
  tls_enabled: true
  tls_cert_file: ./certs/hserver.crt
  tls_key_file: ./certs/hserver.key
logger:
  default_log_level: debug
  print_format: console
  file_path: ./logs/app.log
  max_age: 7
  rotation_time: 1
  logger_level:
    grpc: debug
    main: info
