// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: internal/proto/message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MessageBody   []byte                 `protobuf:"bytes,3,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_internal_proto_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *BaseRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BaseRequest) GetMessageBody() []byte {
	if x != nil {
		return x.MessageBody
	}
	return nil
}

type BaseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResponseCode    int32                  `protobuf:"varint,2,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,3,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	Message         []byte                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_internal_proto_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BaseResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *BaseResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

func (x *BaseResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// meta 信息（用于在流内传输响应的元信息）
type Meta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResponseCode    int32                  `protobuf:"varint,2,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,3,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_internal_proto_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *Meta) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Meta) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *Meta) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

// 流分块，oneof 用于区分是数据块还是 meta 控制块
type Chunk struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MessageType string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ClientId    string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq         int32                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`   // 序号（可用于校验）
	Last        bool                   `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"` // 本方向最后一块
	// Types that are valid to be assigned to Payload:
	//
	//	*Chunk_Data
	//	*Chunk_Meta
	Payload       isChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_internal_proto_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_internal_proto_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Chunk) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Chunk) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Chunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *Chunk) GetPayload() isChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Chunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Chunk) GetMeta() *Meta {
	if x != nil {
		if x, ok := x.Payload.(*Chunk_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

type isChunk_Payload interface {
	isChunk_Payload()
}

type Chunk_Data struct {
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3,oneof"` // 普通数据分片
}

type Chunk_Meta struct {
	Meta *Meta `protobuf:"bytes,6,opt,name=meta,proto3,oneof"` // meta 控制块（通常用于服务端先发送响应状态）
}

func (*Chunk_Data) isChunk_Payload() {}

func (*Chunk_Meta) isChunk_Payload() {}

var File_internal_proto_message_message_proto protoreflect.FileDescriptor

const file_internal_proto_message_message_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/message/message.proto\x12\amessage\"p\n" +
	"\vBaseRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\fmessage_body\x18\x03 \x01(\fR\vmessageBody\"\x92\x01\n" +
	"\fBaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rresponse_code\x18\x02 \x01(\x05R\fresponseCode\x12)\n" +
	"\x10response_message\x18\x03 \x01(\tR\x0fresponseMessage\x12\x18\n" +
	"\amessage\x18\x04 \x01(\fR\amessage\"p\n" +
	"\x04Meta\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rresponse_code\x18\x02 \x01(\x05R\fresponseCode\x12)\n" +
	"\x10response_message\x18\x03 \x01(\tR\x0fresponseMessage\"\xb3\x01\n" +
	"\x05Chunk\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04last\x18\x04 \x01(\bR\x04last\x12\x14\n" +
	"\x04data\x18\x05 \x01(\fH\x00R\x04data\x12#\n" +
	"\x04meta\x18\x06 \x01(\v2\r.message.MetaH\x00R\x04metaB\t\n" +
	"\apayload2I\n" +
	"\x0eMessageService\x127\n" +
	"\x0fSendMessageBidi\x12\x0e.message.Chunk\x1a\x0e.message.Chunk\"\x00(\x010\x01B\x18Z\x16internal/proto/messageb\x06proto3"

var (
	file_internal_proto_message_message_proto_rawDescOnce sync.Once
	file_internal_proto_message_message_proto_rawDescData []byte
)

func file_internal_proto_message_message_proto_rawDescGZIP() []byte {
	file_internal_proto_message_message_proto_rawDescOnce.Do(func() {
		file_internal_proto_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_message_message_proto_rawDesc), len(file_internal_proto_message_message_proto_rawDesc)))
	})
	return file_internal_proto_message_message_proto_rawDescData
}

var file_internal_proto_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_message_message_proto_goTypes = []any{
	(*BaseRequest)(nil),  // 0: message.BaseRequest
	(*BaseResponse)(nil), // 1: message.BaseResponse
	(*Meta)(nil),         // 2: message.Meta
	(*Chunk)(nil),        // 3: message.Chunk
}
var file_internal_proto_message_message_proto_depIdxs = []int32{
	2, // 0: message.Chunk.meta:type_name -> message.Meta
	3, // 1: message.MessageService.SendMessageBidi:input_type -> message.Chunk
	3, // 2: message.MessageService.SendMessageBidi:output_type -> message.Chunk
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_message_message_proto_init() }
func file_internal_proto_message_message_proto_init() {
	if File_internal_proto_message_message_proto != nil {
		return
	}
	file_internal_proto_message_message_proto_msgTypes[3].OneofWrappers = []any{
		(*Chunk_Data)(nil),
		(*Chunk_Meta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_message_message_proto_rawDesc), len(file_internal_proto_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_message_message_proto_goTypes,
		DependencyIndexes: file_internal_proto_message_message_proto_depIdxs,
		MessageInfos:      file_internal_proto_message_message_proto_msgTypes,
	}.Build()
	File_internal_proto_message_message_proto = out.File
	file_internal_proto_message_message_proto_goTypes = nil
	file_internal_proto_message_message_proto_depIdxs = nil
}
